project:
  type: manuscript
  output-dir: docs

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  pdf: default

execute:
  freeze: true

editor: visual

title: "Pregnancy Complicated by Klippelâ€“Trenaunay Syndrome and Kasabach Merritt syndrome Resulting in Severe Fetal Growth Restriction: A case report and review of literature"

bibliography: references.bib

csl: vancouver.csl

